---
title: "Honeybee cross-species analysis - 00a"
author: Aiswarya Prasad
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    <!-- other fun themes: architect leonids hpstr cayman -->
    highlight: github
    math: katex
    number_sections: true
    df_print: paged
    cold-folding: hide
    toc: true
---

# Initialization

To intialize complete all of or relevant sections of `scripts/visualization/Load_data.R`.

# Plot conentrations

### Samples from Malaysia and India

```{r plot1}
ggplot(df_concentrations %>% filter(ID %in% c(samples_IN, samples_MY)), 
        aes(y = factor(ID, rev(c(samples_IN, samples_MY))),
            x = Concentration,
            # fill = factor(Host, host_order),
            shape = Location,
            color = factor(Host, host_order)
          )
        ) +
  geom_point() +
  facet_wrap(~Host, scales = "free") +
  geom_hline(yintercept = 6.5, linetype = "solid") +
   geom_hline(yintercept = 14.5, linetype = "solid") +
   geom_hline(yintercept = 22.5, linetype = "solid") +
   geom_hline(yintercept = 30.5, linetype = "solid") +
    labs(color = "Host species", y = "Sample name", x = "Concentration (ng/uL) - Aliquot of 10 uL") +
    make_theme(setFill = F, setCol = F, guide_nrow = 3) +
    geom_vline(xintercept = 0, linetype = "solid", alpha = 0.5) +
    geom_vline(xintercept = 1, linetype = "solid", color = "#1a9850", alpha = 1) +
    geom_vline(xintercept = 5, linetype = "solid", color = "#fee08b", alpha = 1) +
    geom_vline(xintercept = 10, linetype = "solid", color = "#d73027", alpha = 1) +
      scale_fill_manual(values=host_order_color) +
      scale_color_manual(values=host_order_color_dark)
      ggsave("figures/00a-DNA_Concentrations_compared.pdf")
```

### Samples from Malaysia alone

```{r plot2}
ggplot(df_concentrations %>% filter(ID %in% samples_MY),
        aes(y = factor(ID, rev(samples_MY)),
            x = Concentration,
            # fill = factor(Host, host_order),
            color = factor(Host, host_order)
          )
        ) +
  geom_point() +
  facet_wrap(~Host, scales = "free") +
  geom_hline(yintercept = 6.5, linetype = "solid") +
   geom_hline(yintercept = 14.5, linetype = "solid") +
   geom_hline(yintercept = 22.5, linetype = "solid") +
   geom_hline(yintercept = 30.5, linetype = "solid") +
    labs(color = "Host species", y = "Sample name", x = "Concentration (ng/uL) - Aliquot of 10 uL") +
    make_theme(setFill = F, setCol = F, guide_nrow = 3) +
    geom_vline(xintercept = 0, linetype = "solid", alpha = 0.5) +
    geom_vline(xintercept = 1, linetype = "solid", color = "#d73027", alpha = 1) +
    geom_vline(xintercept = 5, linetype = "solid", color = "#fee08b", alpha = 1) +
    geom_vline(xintercept = 10, linetype = "solid", color = "#1a9850", alpha = 1) +
      scale_fill_manual(values=host_order_color) +
      scale_color_manual(values=host_order_color_dark)
      ggsave("figures/00a-DNA_Concentrations.pdf")
```