---
title: "Honeybee cross-species analysis - 04"
author: Aiswarya Prasad
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    <!-- other fun themes: architect leonids hpstr cayman -->
    highlight: github
    math: katex
    number_sections: true
    df_print: paged
    cold-folding: hide
    toc: true
---

# Initialization

To intialize complete all of or relevant sections of `scripts/visualization/Load_data.R`.

##############
# functions used
##############

source('scripts/visualization/utilities.R', chdir = TRUE)

##############
# files to be read
##############

source('scripts/visualization/05-read_MAG_metadata.R', chdir = TRUE)
contig_fates_df_am <- data.frame()
for (sample in samples_am) {
  contig_fates_df_am <- rbind(contig_fates_df_am, read.csv(paste0("06_MAG_binning/contig_fates/",sample,"_contig_fates.csv"), sep = ","))
}
contig_fates_df_ac <- data.frame()
for (sample in samples_ac) {
  contig_fates_df_ac <- rbind(contig_fates_df_ac, read.csv(paste0("06_MAG_binning/contig_fates/",sample,"_contig_fates.csv"), sep = ","))
}
contig_fates_df_ad <- data.frame()
for (sample in samples_ad) {
  contig_fates_df_ad <- rbind(contig_fates_df_ad, read.csv(paste0("06_MAG_binning/contig_fates/",sample,"_contig_fates.csv"), sep = ","))
}
contig_fates_df_af <- data.frame()
for (sample in samples_af) {
  contig_fates_df_af <- rbind(contig_fates_df_af, read.csv(paste0("06_MAG_binning/contig_fates/",sample,"_contig_fates.csv"), sep = ","))
}
all_depths <- data.frame()
for (sample in samples) {
  sample_contig_depths <- read.csv(paste0("06_MAG_binning/backmapping/",sample,"/",sample,"_mapped_to_",sample,".depth"), sep = "\t")
  depth_column <- paste0(sample,"_mapped_to_",sample,".bam")
  all_depths <- rbind(all_depths, rename(select(sample_contig_depths, contigName, all_of(depth_column)), depth = depth_column))
}

##############
# analyse data and plot
##############


contig_fates_df_am <- cbind(contig_fates_df_am, host = rep("Apis mellifera", dim(contig_fates_df_am)[[1]]))
contig_fates_df_am_pf <- contig_fates_df_am %>%
                              group_by(sample, passed_filter) %>%
                                summarise(pass_fail_length = sum(length), pf_num = n(), .groups = "keep")
contig_fates_df_am_bin <- contig_fates_df_am %>%
                              group_by(sample, binned) %>%
                                summarise(binned_length = sum(length), binned_num = n(), .groups = "keep")
contig_fates_df_ac <- cbind(contig_fates_df_ac, host = rep("Apis cerana", dim(contig_fates_df_ac)[[1]]))
contig_fates_df_ac_pf <- contig_fates_df_ac %>%
                              group_by(sample, passed_filter) %>%
                                summarise(pass_fail_length = sum(length), pf_num = n(), .groups = "keep")
contig_fates_df_ac_bin <- contig_fates_df_ac %>%
                              group_by(sample, binned) %>%
                                summarise(binned_length = sum(length), binned_num = n(), .groups = "keep")
contig_fates_df_ad <- cbind(contig_fates_df_ad, host = rep("Apis dorsata", dim(contig_fates_df_ad)[[1]]))
contig_fates_df_ad_pf <- contig_fates_df_ad %>%
                              group_by(sample, passed_filter) %>%
                                summarise(pass_fail_length = sum(length), pf_num = n(), .groups = "keep")
contig_fates_df_ad_bin <- contig_fates_df_ad %>%
                              group_by(sample, binned) %>%
                                summarise(binned_length = sum(length), binned_num = n(), .groups = "keep")
contig_fates_df_af <- cbind(contig_fates_df_af, host = rep("Apis florea", dim(contig_fates_df_af)[[1]]))
contig_fates_df_af_pf <- contig_fates_df_af %>%
                              group_by(sample, passed_filter) %>%
                                summarise(pass_fail_length = sum(length), pf_num = n(), .groups = "keep")
contig_fates_df_af_bin <- contig_fates_df_af %>%
                              group_by(sample, binned) %>%
                                summarise(binned_length = sum(length), binned_num = n(), .groups = "keep")

contigs_length_df <- rbind(
                        summarise(group_by(contig_fates_df_am, sample), contig = contig_name, length = length, binned = binned, bin = bin_name, passed = passed_filter, .groups = "drop"),
                        summarise(group_by(contig_fates_df_ac, sample), contig = contig_name, length = length, binned = binned, bin = bin_name, passed = passed_filter, .groups = "drop"),
                        summarise(group_by(contig_fates_df_ad, sample), contig = contig_name, length = length, binned = binned, bin = bin_name, passed = passed_filter, .groups = "drop"),
                        summarise(group_by(contig_fates_df_af, sample), contig = contig_name, length = length, binned = binned, bin = bin_name, passed = passed_filter, .groups = "drop")
                  )

length_bin_sum_df <- contigs_length_df %>%
                    mutate(length_bin = cut(length ,breaks=c(0, 500, 1000, 10000, 50000, 100000, 200000, 500000, 1000000, Inf), labels = c("500", "0.5-1kb", "1-10Kb", "10-50Kb", "50-100Kb", "100-200Kb", "200-500Kb", "0.5-1Mb", ">1Mb"))) %>%
                      group_by(sample, binned, length_bin) %>%
                        summarise(length_bin_sum = sum(length), num_contigs = n())
length_bin_sum_df_passed <- contigs_length_df %>%
                    filter(passed == "P") %>%
                    mutate(length_bin = cut(length ,breaks=c(0, 500, 1000, 10000, 50000, 100000, 200000, 500000, 1000000, Inf), labels = c("500", "0.5-1kb", "1-10Kb", "10-50Kb", "50-100Kb", "100-200Kb", "200-500Kb", "0.5-1Mb", ">1Mb"))) %>%
                      group_by(sample, binned, length_bin) %>%
                        summarise(length_bin_sum = sum(length), num_contigs = n())
contigs_depths_df <- left_join(filter(contigs_length_df, passed == "P"), all_depths, by = c("contig" = "contigName"))
rm(all_depths)
contig_fates_df_pf <- rbind(contig_fates_df_am_pf,
                            contig_fates_df_ac_pf,
                            contig_fates_df_ad_pf,
                            contig_fates_df_af_pf
                      )
amount_pass_fail <- ggplot(contig_fates_df_pf, aes(y = factor(sample, samples), x = pass_fail_length, fill = passed_filter)) +
  geom_bar(stat = "identity") +
  labs(y= "Sample", x = "Amount of data passed or failed") +
  # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
  scale_x_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
  make_theme(palettefill = "Set1", leg_pos = "bottom", guide_nrow = 1)
contig_fates_df_bin <- rbind(contig_fates_df_am_bin,
                            contig_fates_df_ac_bin,
                            contig_fates_df_ad_bin,
                            contig_fates_df_af_bin
                      )
contigs_binned_length_plot <- ggplot(contig_fates_df_bin, aes(y = sample, x = binned_length, fill = binned)) +
  geom_bar(stat = "identity") +
    labs(x = "Sample", y = "Amount of data binned or unbinned") +
    scale_x_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
      make_theme(palettefill = "Set1", guide_nrow = 1)
contig_fates_df_am_mag <- contig_fates_df_am %>%
                            # filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
contig_fates_df_ac_mag <- contig_fates_df_ac %>%
                            # filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
contig_fates_df_ad_mag <- contig_fates_df_ad %>%
                            # filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
contig_fates_df_af_mag <- contig_fates_df_af %>%
                            # filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
contigs_binned_length_am_plot_genus <- ggplot(contig_fates_df_am_mag, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04e-contigs_binned_unbinned_by_genus_am.pdf")
contigs_binned_length_am_plot_genus <- ggplot(contig_fates_df_am_mag, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      ggsave("Figures/04-contigs_binned_unbinned_by_genus_am.pdf")

contigs_binned_length_ac_plot_genus <- ggplot(contig_fates_df_ac_mag, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_ac.pdf")

contigs_binned_length_ad_plot_genus <- ggplot(contig_fates_df_ad_mag, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_ad.pdf")

contigs_binned_length_af_plot_genus <- ggplot(contig_fates_df_af_mag, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_af.pdf")

contig_fates_df_am_mag_binned <- contig_fates_df_am %>%
                            filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
rm(contig_fates_df_am)
contig_fates_df_ac_mag_binned <- contig_fates_df_ac %>%
                            filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
rm(contig_fates_df_ac)
contig_fates_df_ad_mag_binned <- contig_fates_df_ad %>%
                            filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
rm(contig_fates_df_ad)
contig_fates_df_af_mag_binned <- contig_fates_df_af %>%
                            filter(binned == "Y") %>%
                            group_by(sample, bin_name) %>%
                              summarise(num_contigs = n(), len_contigs = sum(length), .groups = "keep") %>%
                                left_join(select(vis_magOTUs_df_all, ID, Host, Sample, Cluster, Family, Genus, N50, Prevalence), by = c("bin_name" = "ID"))
rm(contig_fates_df_af)
contigs_binned_length_am_plot_genus_binned <- ggplot(contig_fates_df_am_mag_binned, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_am.pdf")

contigs_binned_length_ac_plot_genus_binned <- ggplot(contig_fates_df_ac_mag_binned, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_ac.pdf")

contigs_binned_length_ad_plot_genus_binned <- ggplot(contig_fates_df_ad_mag_binned, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_ad.pdf")

contigs_binned_length_af_plot_genus_binned <- ggplot(contig_fates_df_af_mag_binned, aes(x = sample, y = len_contigs, fill = factor(Genus, genera))) +
                                  geom_bar(stat = "identity") +
                                    labs(x = "Sample", y = "Sum of length of scaffolds in bin", fill = "Genus") +
                                    # scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6), limits = c(0, 6e+8)) +
                                    scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                                      make_theme(setFill = F,
                                          leg_pos = "right", guide_nrow = 22,
                                          x_angle = 30, x_hj = 1, x_vj = 1
                                        ) +
                                      scale_fill_manual(values=genusColors)
                                      # ggsave("Figures/04-contigs_binned_unbinned_by_genus_af.pdf")

contig_length_host_plot_am <- ggplot(filter(length_bin_sum_df, sample %in% samples_am), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_am.pdf")
contig_length_host_plot_am_passed <- ggplot(filter(length_bin_sum_df_passed, sample %in% samples_am), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_am_passed.pdf")
contig_length_host_plot_ac <- ggplot(filter(length_bin_sum_df, sample %in% samples_ac), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_ac.pdf")
contig_length_host_plot_ac_passed <- ggplot(filter(length_bin_sum_df_passed, sample %in% samples_ac), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_ac_passed.pdf")
contig_length_host_plot_ad <- ggplot(filter(length_bin_sum_df, sample %in% samples_ad), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_ad.pdf")
contig_length_host_plot_ad_passed <- ggplot(filter(length_bin_sum_df_passed, sample %in% samples_ad), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_ad_passed.pdf")
contig_length_host_plot_af <- ggplot(filter(length_bin_sum_df, sample %in% samples_af), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_af.pdf")
contig_length_host_plot_af_passed <- ggplot(filter(length_bin_sum_df_passed, sample %in% samples_af), aes(x = length_bin, y = length_bin_sum, fill = binned)) +
                      geom_bar(stat = "identity") +
                        geom_text(aes(label = num_contigs), angle = 0, size = 1, vjust = 1) +
                        # geom_text(aes(label = num_contigs), angle = 90, size = 2) +
                          labs(x = "length of contig", y = "Total bases from contigs in bin", fill = "binned") +
                            scale_y_continuous(labels=unit_format(unit = "M", scale = 1e-6)) +
                              facet_wrap(~ sample, scales = "free") +
                                make_theme(x_angle = 40, x_size = 7, x_hj = 1, x_vj = 1, leg_pos = "none")
                                  ggsave("Figures/04-contig_length_histogram_af_passed.pdf")

contigs_depths_df_genus <- left_join(contigs_depths_df, select(vis_magOTUs_df_all, ID, Genus, Cluster), by = c("bin" = "ID")) %>%
  ungroup() %>%
  select(!Host) %>%
  left_join(rename(select(df_meta, Sample, SpeciesID), Host = SpeciesID), by = c("sample" = "Sample"))


temp <- ggplot(filter(contigs_depths_df_genus, Host == "Apis mellifera"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              guide_nrow = 7, leg_size = 12,
                              x_size = 5, x_angle = 30, x_hj = 1, x_vj = 1
                            ) +
                            scale_color_manual(values=genusColors)+
                              guides(size = "none", alpha = "none")
genus_legend <- get_only_legend(temp)
remove(temp)

contig_len_vs_depth_am <- ggplot(filter(contigs_depths_df_genus, Host == "Apis mellifera"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_am), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_all_am.pdf")
contig_len_vs_depth_am_binned <- ggplot(filter(contigs_depths_df_genus, Host == "Apis mellifera" & binned != "N"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_am), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_binned_am.pdf")
contig_len_vs_depth_ac <- ggplot(filter(contigs_depths_df_genus, Host == "Apis cerana"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_ac), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_all_ac.pdf")
contig_len_vs_depth_ac_binned <- ggplot(filter(contigs_depths_df_genus, Host == "Apis cerana" & binned != "N"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_ac), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_binned_ac.pdf")
contig_len_vs_depth_ad <- ggplot(filter(contigs_depths_df_genus, Host == "Apis dorsata"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_ad), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_all_ad.pdf")
contig_len_vs_depth_ad_binned <- ggplot(filter(contigs_depths_df_genus, Host == "Apis dorsata" & binned != "N"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_ad), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_binned_ad.pdf")
contig_len_vs_depth_af <- ggplot(filter(contigs_depths_df_genus, Host == "Apis florea"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_af), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_all_af.pdf")
contig_len_vs_depth_af_binned <- ggplot(filter(contigs_depths_df_genus, Host == "Apis florea" & binned != "N"), aes(x = bin, y = depth, color = Genus, size = length, alpha = 0.5)) +
                          geom_point() +
                            make_theme(setFill = F, setCol = F,
                              leg_pos = "bottom",
                              x_size = 5, x_angle = 50, x_hj = 1, x_vj = 1
                            ) +
                            scale_size_continuous(labels=unit_format(unit = "K", scale = 1e-4)) +
                            theme(legend.margin=margin(-1,-1,-1,-1), legend.box="vertical") +
                            scale_color_manual(values=genusColors) +
                            scale_y_continuous(trans="log10")+
                            facet_wrap(~ factor(sample, samples_af), scales="free") +
                              guides(color = "none", alpha = "none")
                              ggsave("Figures/04-length_vs_depth_contigs_binned_af.pdf")