#!/bin/bash

remote_server_nas=aiswarya@130.223.110.124:/home/aiswarya/mnt
# change this to copy from backup of backup
specifier=/ # or specifier=BACKUP/

mkdir -p /scratch/aprasad/211018_Medgenome_india_samples | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
cd /scratch/aprasad/211018_Medgenome_india_samples  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log

mkdir -p envs  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
mkdir -p scripts  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
mkdir -p Figures  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
mkdir -p logs  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
mkdir -p database  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
mkdir -p 00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log


# rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}01_Trimmed /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
# or
# rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}00_RawData /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
# List raw file paths here or later, in an external file or table
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C1.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C1.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C1.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C1.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C1.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C2.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C2.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C2.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C3.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C3.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/C3.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C3.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/C3.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D1.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D2.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D2.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D2.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D2.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D2.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D3.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D3.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/D3.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D3.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/D3.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F1.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F1.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F1.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F2.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F2.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F2.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F3.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F3.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F3.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/F3.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211102_Medgenome_india_samples_resequenced/00_rawdata/F3.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.1_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.1_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.2_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.2_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.3_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.3_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.4_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.4_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.5_R1.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress /nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/211018_Medgenome_india_samples/00_rawdata/M1.5_R2.fastq.gz /scratch/aprasad/211018_Medgenome_india_samples/00_RawData  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log


rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}envs/* /scratch/aprasad/211018_Medgenome_india_samples/envs/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}scripts/* /scratch/aprasad/211018_Medgenome_india_samples/scripts/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log

# for database in ...

rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/genome_db_220315_AP /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/genome_db_220315_AP*metafile* /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/4_host_db /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log


# For KE's core coverage estimation

rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/bed_files /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress --exclude "*_ortho_sequences*" --exclude "*OrthoFinder*" ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/faa_files /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/ffn_files /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}database/gff_files /scratch/aprasad/211018_Medgenome_india_samples/database/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log

rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}211018_Medgenome_india_samples_Report.Rmd /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}make_phylo_table.R /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}IsolateGenomeInfo.csv /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}Adapters-PE.fa /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}Snakefile /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}config.yaml /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}Metadata_211018_Medgenome_india_samples.csv /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}MakePhylogenies.smk /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
rsync -a -v --progress ${remote_server_nas}/aprasad/Backups/working_dir_backup/Cluster/211018_Medgenome_india_samples/${specifier}index_table.csv /scratch/aprasad/211018_Medgenome_india_samples/  | tee -a /scratch/aprasad/211018_Medgenome_india_samples/project_initialization.log
