# # input
# 49,7245495,D3.4,LIB267705,KAPA  P7 UDI73 A10,CTACCAGG,KAPA P5 UDI73 A10,CAACTGAT
# 50,7245496,D3.5,LIB267706,KAPA  P7 UDI74 B10,ACTGTATC,KAPA P5 UDI74 B10,TGCTATTA

# # output
# >PREFIX_D3.4_P5_UDI73_PE/1
# GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTACCAGGATCTCGTATGCCGTCTTCTGCTTG
# >PREFIX_D3.4_P7_UDI73_PE/2
# GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTACCAGGATCTCGTATGCCGTCTTCTGCTTG
# >PREFIX_D3.5_P5_UDI74_PE/1
# GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGTATCATCTCGTATGCCGTCTTCTGCTTG
# >PREFIX_D3.5_P7_UDI74_PE/2
# GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGTATCATCTCGTATGCCGTCTTCTGCTTG
# >PrefixPE/1
# TACACTCTTTCCCTACACGACGCTCTTCCGATCT
# >PrefixPE/2
# GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
# >PE1
# TACACTCTTTCCCTACACGACGCTCTTCCGATCT
# >PE1_rc
# AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA
# >PE2
# GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
# >PE2_rc
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

# use bioseq revcomp..

print("this script was deleted earlier")
print("The output luckily survived (Adapters-PE.fa)")
