#!/usr/bin/env Rscript
options(warn=1)
rm(list=ls())

script_usage <- function() {
    cat("\nUsage: Rscript core_cov.R 4_firm5_single_ortho_filt_corecov.txt   [--no_plots]\n", fill=TRUE)
    cat("Input-file should correspond to the output-file generated by 'core_cov.py'", fill=TRUE)
    cat("If the --no_plots flag is provided, all plots will be skipped", fill=TRUE)
}

Args <- commandArgs(trailingOnly=TRUE)
if (length(Args) == 0 || Args[1] == "--help") {
     script_usage()
     quit()
}

if (length(Args) == 1) {
    split_filename <- strsplit(Args[1],"\\_corecov.")[[1]]
    outfile_prefix <- split_filename[1]
}
if (length(Args) == 2 && Args[2] == "--no_plots") {
    split_filename <- strsplit(Args[1],"\\.")[[1]]
    outfile_prefix <- split_filename[1]
}
if (length(Args) == 2 && Args[2] != "--no_plots") {
    outfile_prefix = Args[2]
}
if (length(Args) == 3 && Args[2] == "--no_plots") {
  do_plots <- 0
  outfile_prefix = Args[3]
}
if (length(Args) == 3 && Args[3] == "--no_plots") {
  do_plots <- 0
  outfile_prefix = Args[2]
}

#Check if the R-packages are installed
if (! require("segmented")) {
    print("The R-package 'segmented' is not installed! Exiting script")
    quit()
} else {
    require("segmented")
}
if (! require("plyr")) {
    print("The R-package 'plyr' is not installed! Exiting script")
    quit()
} else {
    require("plyr")
}
if (! require("Cairo")) {
    print("The R-package 'Cairo' is not installed! Exiting script")
    quit()
} else {
    require("Cairo")
}
